_target_: pytorch_lightning.Trainer
devices: 1
strategy: auto
accelerator: gpu
max_epochs: 200
min_epochs: 4
check_val_every_n_epoch: 1
logger:
  _target_: pytorch_lightning.loggers.WandbLogger
  save_dir: ~/scratch/logs
  project: omics-guided-gfn
  entity: your.wandb.entity
  # mode: disabled
