_target_: pytorch_lightning.Trainer
devices: 1
strategy: auto
accelerator: gpu
max_epochs: 50
min_epochs: 4
check_val_every_n_epoch: 1
logger:
  _target_: pytorch_lightning.loggers.WandbLogger
  save_dir: /home/mila/s/stephen.lu/gfn_gene/multimodal_contrastive/logs
  project: omics-guided-gfn
  entity: thematrixmaster
