_target_: pytorch_lightning.Trainer
devices: 1
strategy: auto
accelerator: gpu
max_epochs: 1
min_epochs: 1
check_val_every_n_epoch: 1
logger:
  _target_: pytorch_lightning.loggers.WandbLogger
  save_dir: ~/scratch/log
  project:
  entity: