latent_dist_correlation:
    _target_: multimodal_contrastive.evaluation.evaluation.LatentDistCorrelationEvaluator
    modes:
        - "struct"
        - "ge"
        - "morph"
        - "joint"
    seed: 0
