defaults:
  - datamodule: puma.yaml
  - model: gmc_smg.yaml
  - callbacks: default.yaml
  - trainer: default.yaml
  - evaluations:
    - latent_dist_correlation.yaml
    - retrieval_evaluation.yaml
  - _self_

datamodule:
  split_type: shuffled_scaffold
  dataset:
    mods:
    - struct
    - morph
    - ge
    joint_as_input: True
  batch_size: 128
  num_workers: 8
  split_sizes:
      - 0.8
      - 0.1
      - 0.1

model:
  loss_name: gmc
  morph_input_dim: 1746
  temperature: 0.4
  lr: 0.000002
  dim: 1024
  # nonlin: ReLU
  # num_input_features: 1746 #puma morph input feature size

callbacks:
    model_checkpoint:
        monitor: struct-morph~pca_morph~val
        mode: max

trainer:
  max_epochs: 150
  accelerator: gpu
  logger:
    save_dir: ~/scratch/mmc
    project: omics-guided-gfn
    entity: your.wandb.entity

evaluations:
  latent_dist_correlation:
      modes:
        - "joint"
        - "morph"
        - "struct"
        - "ge"
  retrieval_evaluation:
    retrieval_pairs:
        - ['struct', 'morph']
        - ['morph', 'struct']
        - ['struct', 'ge']
        - ['ge', 'struct']
      
# simply provide checkpoint path to resume training
ckp_path:

seed: 39
