defaults:
  - datamodule: puma.yaml
  - model: gmc_sm.yaml
  - callbacks: default.yaml
  - trainer: default.yaml
  - evaluations:
    - latent_dist_correlation.yaml
    - retrieval_evaluation.yaml
  - _self_

datamodule:
  split_type: Sorted_cluster
  balance: True
  dataset:
    mods:
    - struct
    - morph
    joint_as_input: True
    cluster: path.to.datasets/cluster_idx.pkl
  batch_size: 128
  num_workers: 8
  split_sizes:
      - 0.8
      - 0.1
      - 0.1
  seed: 0

model:
  loss_name: gmc
  morph_input_dim: 1746
  temperature: 0.4
  lr: 0.000002
  dim: 1024
  nonlin: ReLU
  num_input_features: 1746 # puma morph input feature size
  # num_input_features: 3483 # for jump morph

callbacks:
    model_checkpoint:
        # monitor: struct-morph~pca_morph~val
        # mode: max
        monitor: val/loss
        mode: min

trainer:
  max_epochs: 200
  accelerator: gpu
  logger:
    save_dir: ~/scratch/mmc
    project: omics-guided-gfn
    entity: your.wandb.entity

evaluations:
  latent_dist_correlation:
      modes:
        - "joint"
        - "morph"
        - "struct"
  retrieval_evaluation:
    retrieval_pairs:
        - ['struct', 'morph']
        - ['morph', 'struct']
      
# simply provide checkpoint path to resume training
ckp_path:

seed: 0