defaults:
  - datamodule: puma.yaml
  - model: clip_sg.yaml
  - callbacks: default.yaml
  - trainer: default.yaml
  - evaluations: retrieval_evaluation.yaml
  - _self_

datamodule:
  split_type: scaffold # can be random, scaffold, fingerprint, or butina, default is random
  dataset:
    mods:
    - struct
    - ge
    joint_as_input: False # need to set to be False for clip style model
  batch_size: 128
  num_workers: 8
  split_sizes:
      - 0.8
      - 0.1
      - 0.1

model:
  loss_name: clip # set loss_name==clip for clip style model
  morph_input_dim: 1746
  temperature: 0.2
  lr: 0.0001
  dim: 128
  nonlin: ReLU
  num_input_features: 1746 #puma morph input feature size

callbacks:
    model_checkpoint:
        monitor: val/loss
        mode: min

trainer:
  max_epochs: 50
  logger:
    save_dir: /home/mila/s/stephen.lu/scratch/mmc
    project: omics-guided-gfn
    entity: thematrixmaster

evaluations:
  retrieval_evaluation:
    retrieval_pairs:
        - ['struct', 'morph']
        - ['morph', 'struct']
      
# simply provide checkpoint path to resume training
ckp_path:

seed: 0
