_target_: multimodal_contrastive.data.datamodule.MultiInput_DataModule
dataset:
    _target_: multimodal_contrastive.data.dataset.H5DatasetJUMP
    data: ~/scratch/mmc/datasets/jump_pp_fast_public.h5
batch_size: 128
num_workers: 8
split_sizes:
    - 0.9
    - 0.05
    - 0.05