_target_: multimodal_contrastive.data.datamodule.MultiInput_DataModule
dataset:
    _target_: multimodal_contrastive.data.dataset.H5DatasetJUMP
    data: /projects/global/gred/resbioai/multimodal/mocop/jump/h5/jump_pp_fast_20231213.h5
batch_size: 128
num_workers: 8
split_sizes:
    - 0.9
    - 0.05
    - 0.05