_target_: multimodal_contrastive.data.datamodule.MultiInput_DataModule
dataset:
    _target_: multimodal_contrastive.data.dataset.TestDataset
    data: /projects/global/gred/resbioai/multimodal/PUMA_data/assay_data/assay_matrix_discrete_37_assays_canonical.csv
    mol_col: smiles
    label_col:
batch_size: 512
num_workers: 8
split_sizes:
    - 0.8
    - 0.1
    - 0.1
