program: /home/mila/s/stephen.lu/gfn_gene/multimodal_contrastive/multimodal_contrastive/pretrain.py
description: puma_paper_sweeps
project: puma_paper_sweeps
entity: thematrixmaster

method: bayes
metric:
  goal: maximize
  name: ge>struct_mrr
  
parameters:
  datamodule.batch_size:
    values: [128]
  model.lr:
    min: 0.0001
    max: 0.1
  model.temperature:
    distribution: uniform
    min: 0.01
    max: 1
  model.loss_name:
    values: ['VICReg']
  model.loss_args.invar_coeff:
    values: [25, 50]
  model.loss_args.var_coeff:
    values: [25, 50]
  model.loss_args.cov_coeff:
    values: [1, 5]
  model.dim:
    values: [128, 256]
  model.optimizer_args.name:
    values: ['lars', 'adam']
  model.optimizer_args.wd:
    values: [1000000]
  model.optimizer_args.num_warmup_steps_or_ratio:
    values: [0.1]
  
command:
  - ${env}
  - python
  - ${program}
  - "--config-name"
  - "paper_train_sg"
  - ${args_no_hyphens}

